#!/bin/bash

#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# https://github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------
# This file represents a GitPack extension, which incorporates a prompting tab
# completion of GitPak arguments into Bash shells. It is expected to be sourced.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# ENTRY POINT
#-------------------------------------------------------------------------------

_gitpack() {
    local -r COMMANDS='install uninstall status list clean paths help about' &&
    local native_mode cur words cword command_index &&

    _gitpack_init_comp &&
    command_index="$(_gitpack_subcommand_index)" &&

    if ! [ "$command_index" ]; then # no action or command so far
        _gitpack_set_compreply -W "$COMMANDS" -- "$cur"
    else # repository URLs
        local command="${COMP_WORDS[command_index]}" &&
        case "$command" in # only for GitPack actions
            install | uninstall | status) _gitpack_url ;;
        esac
    fi &&

    if [ "$native_mode" = true ]; then
        __ltrim_colon_completions "$cur" # make hints with colon in word work
    fi
}

#-------------------------------------------------------------------------------
# INITIALIZATION
#-------------------------------------------------------------------------------

_gitpack_init_comp() {
    if command -v _get_comp_words_by_ref > /dev/null &&
       command -v __ltrim_colon_completions > /dev/null; then # more features
        native_mode=true
        _get_comp_words_by_ref -n : cur words cword # do not split by colons
    else # less features as a fallback
        native_mode=false
        cur="${COMP_WORDS[COMP_CWORD]}"
        words=("${COMP_WORDS[@]}")
        cword="$COMP_CWORD"
    fi
}

#-------------------------------------------------------------------------------
# URL COMPLETION
#-------------------------------------------------------------------------------

_gitpack_subcommand_index() {
    local accept_next=false item &&
    for ((i=1; i<cword; i++)); do # ignore first and last items
        item="${words[i]}" &&
        if [ "$accept_next" = true ]; then
            echo "$i"; return
        fi &&
        if [ "$item" = "${item#-}" ]; then # no dash prefix
            echo "$i"; return
        elif [ "$item" = '--' ]; then
            accept_next=true
        fi || return
    done
}

_gitpack_url() {
    # collect global and local GitPack URL references to form a hint
    local urls && urls="$(
        cut -f 1 -d ' ' \
            /var/lib/gitpack/status \
            /var/cache/gitpack/fetched \
            "$HOME"/.local/share/gitpack/status \
            "$HOME"/.cache/gitpack/fetched 2>/dev/null
        true
    )" &&
    _gitpack_set_compreply -W "$urls" -- "$cur"
}

# $@ - compgen arguments
_gitpack_set_compreply() {
    local line &&
    COMPREPLY=() && # initialize as an empty array
    while IFS= read -r line; do
        COMPREPLY+=("$line")
    done < <(compgen "$@")
}

#-------------------------------------------------------------------------------
# REGISTER COMPLETION
#-------------------------------------------------------------------------------

# load the gitpack completion into the current Bash environment
complete -F _gitpack gitpack
