#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020-2021 Dominik Salvet
# https://github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

echo 'copying files' &&
mkdir -p /usr/local/bin/ \
         /etc/bash_completion.d/ &&
cp src/gitpack /usr/local/bin/ &&
cp src/bash/gitpack-completion /etc/bash_completion.d/
