#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020 Dominik Salvet
# https://github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

echo 'removing files' &&
rm -f "$HOME/.local/bin/gitpack" &&
rm -f "$HOME/.bash_completion.d/gitpack-completion"
