#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020-2021 Dominik Salvet
# https://github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

echo 'removing files' &&
rm -f /usr/local/bin/gitpack \
      /etc/bash_completion.d/gitpack-completion
