#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020-2021 Dominik Salvet
# https://github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

echo 'removing files' &&
rm -f "$HOME/.local/bin/gitpack" \
      "$HOME/.bash_completion.d/gitpack-completion"
