#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

# if there is no Bash completion file in home directory, create one
if [ ! -e ~/.bash_completion ]; then
    cp .gitpack/data/.bash_completion ~/
fi
