#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
# just a try
#-------------------------------------------------------------------------------

# if there is no Bash completion file in home directory, create one
if [ ! -e "$HOME"/.bash_completion ]; then
    cp .gitpack/data/.bash_completion "$HOME"/
fi
