version: 2.1

orbs:
  shellcheck: circleci/shellcheck@volatile

workflows:
  analysis:
    jobs:
      - shellcheck/check:
          pattern: .ci/*.sh src/* .gitpack/data/.bash_completion .gitpack/install/local/precp
