#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

version: 2.1

jobs:
  analyse:
    docker:
    - image: ubuntu
    steps:
    - checkout
    - run: apt install -y shellcheck
    - run:
        shell: /bin/sh
        command: .circleci/analysis.sh

workflows:
  analysis:
    jobs:
    - analyse
