#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

version: 2.1

workflows:
  push:
    jobs:
    - analysis
    - test:
        requires:
        - analysis

jobs:
  analysis:
    docker:
    - image: koalaman/shellcheck-alpine:v0.7.0
    steps:
    - checkout
    - run: .circleci/analysis.sh
  test:
    docker:
    - image: alpine/git:1.0.7
    steps:
    - checkout
    - run: .circleci/test.sh
