#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

version: 2.1

jobs:
  analysis:
    docker:
    - image: koalaman/shellcheck-alpine
    resource_class: small
    steps:
    - checkout
    - run: shellcheck .circleci/*.sh
    - run: shellcheck src/*
    - run: shellcheck .gitpack/data/.bash_completion
    - run: shellcheck .gitpack/install/local/precp

workflows:
  default:
    jobs:
    - analysis
