#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

version: 2.1

orbs:
  shellcheck: circleci/shellcheck@volatile

workflows:
  analysis:
    jobs:
      - shellcheck/check:
          path: .circleci
          pattern: \*.sh
