#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

version: 2

workflows:
  version: 2
  push:
    jobs:
    - analysis

jobs:
  analysis:
    docker:
    - image: koalaman/shellcheck-alpine:v0.7.0
    steps:
    - checkout
    - run: .circleci/analysis.sh
