#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

version: 2.1

jobs:
  shellcheck:
    docker:
    - image: koalaman/shellcheck
    steps:
    - checkout
    - run: shellcheck .circleci/*.sh
    - run: shellcheck src/*
    - run: shellcheck .gitpack/data/.bash_completion .gitpack/install/local/precp

workflows:
  default:
    jobs:
      - shellcheck
