version: 2.1

orbs:
  shellcheck: circleci/shellcheck@volatile

jobs:
  build:
    docker:
      - image: 'koalaman/shellcheck-alpine:v0.7.0'
    steps:
      - checkout
      - run: echo "$PWD"
      - run: ls -al

workflows:
  shellcheck:
    jobs:
      - shellcheck/check
  pwd:
    jobs:
      - build

