#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

version: 2.1

workflows:
  push:
    jobs:
    - analysis
    - test:
        requires:
        - analysis

jobs:
  analysis:
    docker:
    - image: koalaman/shellcheck-alpine:v0.7.0
    parallelism: 4
    steps:
    - checkout
    - run: .circleci/analysis.sh
    - run: sleep 5 && false
    - run: sleep 10 && echo hi
    - run: sleep 3 && true
    - run: sleep 15 && echo done
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run: .circleci/test.sh 2>&1 1>/dev/null
