#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

jobs:
  analysis:
    docker:
    - image: koalaman/shellcheck-alpine:v0.7.0
    steps:
    - checkout
    - run: .circleci/analysis.sh

workflows:
  default:
    jobs:
    - analysis
