#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# https://github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------
# This is GitPack, a simple Git-based package manager. It is particularly useful
# for installing scripts across various platforms. This script is all you need
# to have GitPack running. All arguments are processed as GitPack help explains.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# MAIN FUNCTION
#-------------------------------------------------------------------------------

# $@ - GitPack arguments
main() {
    init_constants &&
    init_config &&
    init_env_vars &&
    init_opts &&
    process_args "$@"
}

#-------------------------------------------------------------------------------
# STATIC INITIALIZATION
#-------------------------------------------------------------------------------

init_constants() {
    readonly VERSION=0.7.0 # current GitPack version

    readonly HELP_MESSAGE='USAGE:    gitpack [OPTION...] ACTION URL[=VERSION]...
          gitpack [OPTION...] COMMAND

ACTION:   install    install/update package
          uninstall  uninstall package
          status     get package status

COMMAND:  list   list installed packages
          clean  clean cache
          paths  show file paths
          help   show help
          about  show information

OPTION:   -h  show short version hashes
          -H  show full version hashes
          -f  always fetch remote updates
          -r  raw URL mode; use with caution'

    readonly ABOUT_MESSAGE="GitPack $VERSION
Simple Git-based package manager.

Copyright 2019-2020 Dominik Salvet
https://github.com/dominiksalvet/gitpack"
}

init_config() {
    # URLs matching this regular expression are rejected
    readonly BAD_URL_REGEX='(^$| |(^|/)\.\.?($|/))' # ERE regex

    # map remote references to local ones
    readonly ORIGIN_HEAD=refs/remotes/origin/HEAD # remote HEAD reference path
    readonly HEAD_REFSPEC=+HEAD:"$ORIGIN_HEAD" # default remote branch
    readonly TAGS_REFSPEC='+refs/tags/*:refs/tags/*' # versions
    readonly HEADS_REFSPEC='+refs/heads/*:refs/heads/*' # branches

    # field column numbers of GitPack databases
    readonly STATUS_COL_URL=1 STATUS_COL_HASH=2
    readonly FETCHED_COL_URL=1 FETCHED_COL_TIME=2

    readonly DB_DELIMITER=' ' # internal delimiter for database data
}

init_env_vars() {
    export DIAG_PREFIX= # prefix for diagnostic messages (exported to scripts)
}

init_opts() {
    # global variables
    hash_mode= # short, full
    fetch_always_mode=false
    raw_url_mode=false
}

#-------------------------------------------------------------------------------
# ARGUMENT PROCESSING
#-------------------------------------------------------------------------------

# $@ - GitPack arguments
process_args() (
    process_opts "$@" &&
    shift "$((OPTIND - 1))" && # shift to an actual subcommand

    case "$1" in
        install | uninstall | status)
            process_action_args "$@" ;;
        list | clean | paths)
            process_command_args "$@" ;;
        help) echo "$HELP_MESSAGE" ;;
        about) echo "$ABOUT_MESSAGE" ;;
        '') echoh 'E2: no subcommand provided'; return 1 ;;
        *) echoh "E3: invalid subcommand $1"; return 1 ;;
    esac
)

# $@ - GitPack options
process_opts() {
    while getopts :hHfr _opt; do
        case "$_opt" in
            h) hash_mode=short ;;
            H) hash_mode=full ;;
            f) fetch_always_mode=true ;;
            r) raw_url_mode=true ;;
            ?) echoh "E13: invalid option -$OPTARG"; return 1 ;;
        esac || return
    done
}

# $1 - action
# $@ - action arguments
process_action_args() (
    init_runtime &&
    action="$1" &&
    shift && # shift to URL arguments

    if [ "$#" -eq 0 ]; then
        echoh 'E4: no URL provided'; return 1
    fi &&

    for url_arg in "$@"; do
        perform_action "$action" "$url_arg" || return
    done
)

# $1 - command
# $@ - command arguments
process_command_args() (
    init_runtime &&
    case "$1" in # other arguments are ignored
        list) run_list ;;
        clean) run_clean ;;
        paths) run_paths ;;
    esac
)

# $@ - echo arguments
echoh() {
    echo "$@" >&2 &&
    echo "try 'gitpack help' for more information" >&2 # print also a hint
}

#-------------------------------------------------------------------------------
# DYNAMIC INITIALIZATION
#-------------------------------------------------------------------------------

init_runtime() {
    check_commands &&
    init_runtime_constants &&
    init_paths &&
    init_files
}

check_commands() {
    if ! command -v git > /dev/null; then
        echo 'E1: missing git command' >&2; return 1
    fi
}

init_runtime_constants() {
    _user_id="$(id -u)" &&
    if [ "$_user_id" -eq 0 ]; then
        readonly ACCESS=global
    else
        readonly ACCESS=local
    fi &&

    SYSTEM="$(uname)" &&
    readonly SYSTEM
}

init_paths() {
    if [ "$ACCESS" = global ]; then # respect FHS
        readonly STATE_DIR=/var/lib/gitpack
        readonly CACHE_DIR=/var/cache/gitpack
    else # respect XDG
        readonly STATE_DIR="$HOME"/.local/share/gitpack
        readonly CACHE_DIR="$HOME"/.cache/gitpack
    fi

    readonly STATUS_PATH="$STATE_DIR"/status # database of installed packages
    readonly REPOS_DIR="$CACHE_DIR"/repos # cache for local repositories
    readonly FETCHED_PATH="$CACHE_DIR"/fetched # repositories fetch timestamps
}

init_files() {
    init_db "$STATUS_PATH" &&
    init_db "$FETCHED_PATH"
}

#-------------------------------------------------------------------------------
# COMMAND PROCESSING
#-------------------------------------------------------------------------------

run_list() (
    db="$(get_db "$STATUS_PATH")" &&
    echon "$db" | while IFS= read -r record; do
        url="$(status_record_url "$record")" &&
        hash="$(status_record_hash "$record")" &&
        version="$(beautify_hash "$url" "$hash")" &&
        echo "$url $version" || return
    done
)

run_clean() {
    if ! remove_dir "$CACHE_DIR"; then
        echo 'E5: failed to remove cache directory' >&2; return 1
    fi
}

run_paths() {
    echo "state-dir $STATE_DIR" &&
    echo "cache-dir $CACHE_DIR"
}

# $@ - echo arguments
echon() {
    # no newline if empty string
    if [ "$*" ]; then
        echo "$@"
    fi
}

# $1 - URL
# $2 - hash (optional)
beautify_hash() (
    if [ "$2" ]; then
        if ! [ "$hash_mode" ] && repo_cd "$1" 2>/dev/null &&
           ref="$(git describe --all --exact-match "$2" 2>/dev/null)"; then
            echo "${ref##*/}" # remove reference path prefix
        elif [ "$hash_mode" = full ]; then
            echo "$2" # return full hash
        else
            echo "$2" | cut -c 1-7 # return short hash
        fi
    fi
)

# $1 - directory path
remove_dir() {
    echod "removing directory $1" &&
    test "$1" && if ! [ -d "$1"/ ]; then return; fi &&

    # do not remove any important directory
    (   cd -- "$1"/ && real_path="$(pwd -P)" &&
        test "$PWD" != / && test "$real_path" != / &&
        test "$PWD" != // && test "$real_path" != // &&
        test "$PWD" != "$HOME" && test "$real_path" != "$HOME"
    ) &&

    rm -rf -- "${1:?}"/
}

# $1 - string
echod() {
    # print diagnostic message with defined prefix (progress reporting)
    echo "${DIAG_PREFIX}$1" >&2
}

#-------------------------------------------------------------------------------
# ACTION PROCESSING
#-------------------------------------------------------------------------------

# $1 - action
# $2 - URL argument
perform_action() (
    echo "running $1 for $2" &&
    DIAG_PREFIX='  ' && # increase prefix indentation
    url="$(url_arg_to_url "$2")" &&
    version="$(url_arg_to_version "$2")" && # may be empty
    check_url "$url" &&

    init_repo "$url" &&
    record="$(get_status_record "$url")" && # get package local information
    src_hash="$(status_record_hash "$record")" &&
    tar_hash="$(get_repo_hash "$url" "$version")" &&

    case "$1" in
        install) perform_install "$url" "$src_hash" "$tar_hash" ;;
        uninstall) perform_uninstall "$url" "$src_hash" ;;
        status) perform_status "$url" "$src_hash" "$tar_hash" ;;
    esac
)

# $1 - URL argument
url_arg_to_url() (
    url="${1%=*}" # remove version if any

    if [ "$raw_url_mode" = false ]; then
        url="$(echo "$url" | tr '[:upper:]' '[:lower:]')" &&
        url="${url#https://}" &&
        url="${url%.git}"
    fi &&

    echo "$url"
)

# $1 - URL argument
url_arg_to_version() (
    version="${1##*=}" # remove URL and keep version
    if [ "$version" != "$1" ]; then
        echo "$version"
    fi
)

# $1 - URL
check_url() (
    lineno="$(echo "$1" | wc -l)" &&
    if [ "$lineno" -ne 1 ] || echo "$1" | grep -qE "$BAD_URL_REGEX"; then
        echo 'E6: unsupported URL delivered' >&2; return 1
    fi
)

#-------------------------------------------------------------------------------
# REPOSITORY
#-------------------------------------------------------------------------------

# $1 - URL
init_repo() (
    if [ "$fetch_always_mode" = false ] && fetched_recently "$1"; then
        echod 'local repository fresh'
    else
        repo_dir="$(url_to_path "$1")" &&
        fetch_repo "$1" "$repo_dir" &&
        mark_as_fetched_now "$1"
    fi
)

# $1 - URL
# $2 - repository directory
fetch_repo() (
    if [ -d "$2"/ ]; then # repository already exists
        echod 'updating local repository' &&
        cd -- "$2"/
    else # create and configure repository
        echod 'downloading local repository' &&
        mkdir -p -- "$2"/ && cd -- "$2"/ &&
        # initialize Git repository manually
        git init -q &&
        git config gc.auto 0 && # disable garbage collector
        git config remote.origin.url "$(url_to_git_url "$1")" &&
        git config remote.origin.fetch "$HEAD_REFSPEC" &&
        git config --add remote.origin.fetch "$TAGS_REFSPEC" &&
        git config --add remote.origin.fetch "$HEADS_REFSPEC"
    fi &&
    # fetch remote updates (prune, do not fetch tags implicitly, update HEAD)
    git fetch -pnuq origin
)

# $1 - URL
url_to_git_url() {
    if [ "$raw_url_mode" = true ]; then
        echo "$1"
    else
        echo https://"$1".git
    fi
}

# $1 - URL
# $2 - version (optional)
get_repo_hash() (
    repo_cd "$1" &&
    if [ "$2" = HEAD ]; then # HEAD reference must point to remote HEAD
        set -- "$1" "$ORIGIN_HEAD"
    fi &&

    if [ "$2" ]; then
        echod 'using given candidate version' &&
        # print the commit hash of the version if it is a valid Git reference
        if ! git rev-parse -q --verify "$2"^0; then
            echo "E8: version $2 does not exist" >&2; return 1
        fi
    else # use latest tag (preferred) or latest commit of default branch
        echod 'using latest candidate version' &&
        ref="$(git describe --tags --abbrev=0 --always "$ORIGIN_HEAD")" &&
        git rev-parse --verify "$ref"^0 # get commit hash
    fi
)

# $1 - URL
# $2 - hash (optional)
repo_cd() {
    cd "$(url_to_path "$1")"/ &&
    if [ "$2" ]; then
        git checkout -qf "$2"
    fi
}

# $1 - URL
url_to_path() {
    echo "$REPOS_DIR"/"$1"
}

#-------------------------------------------------------------------------------
# EXECUTE ACTION
#-------------------------------------------------------------------------------

# $1 - URL
# $2 - source hash (optional)
# $3 - target hash
perform_install() {
    if ! [ "$2" ]; then # not installed yet
        run_install "$1" "$3" &&
        insert_status_record "$1" "$3" &&
        echo 'done; successfully installed'
    elif [ "$2" = "$3" ]; then
        echo 'already installed'
    else
        perform_change "$1" "$2" "$3"
    fi
}

# $1 - URL
# $2 - source hash (optional)
perform_uninstall() {
    if [ "$2" ]; then # if installed
        run_uninstall "$1" "$2" &&
        delete_status_records "$1" &&
        echo 'done; successfully uninstalled'
    else
        echo 'already uninstalled'
    fi
}

# $1 - URL
# $2 - source hash (optional)
# $3 - target hash
perform_status() (
    src_version="$(beautify_hash "$1" "$2")" && # success even when empty
    tar_version="$(beautify_hash "$1" "$3")" &&

    if ! [ "$2" ]; then # no source version
        echo "not installed; candidate is $tar_version"
    elif [ "$2" = "$3" ]; then # given versions are equal
        echo "candidate $tar_version already installed"
    elif is_ancestor_commit "$1" "$2" "$3"; then # source version is older
        echo "installed $src_version is older than candidate $tar_version"
    elif is_ancestor_commit "$1" "$3" "$2"; then # source version is newer
        echo "installed $src_version is newer than candidate $tar_version"
    else # given versions are not comparable
        echo "installed $src_version differs from candidate $tar_version"
    fi
)

# $1 - URL
# $2 - source hash
# $3 - target hash
perform_change() (
    if is_ancestor_commit "$1" "$2" "$3"; then # source version is older
        echod 'updating package' &&
        report='done; successfully updated'
    elif is_ancestor_commit "$1" "$3" "$2"; then # source version is newer
        echod 'downgrading package' &&
        report='done; successfully downgraded'
    else # given versions are not comparable
        echod 'changing package version' &&
        report='done; successfully changed'
    fi &&

    run_uninstall "$1" "$2" &&
    delete_status_records "$1" &&
    run_install "$1" "$3" &&
    insert_status_record "$1" "$3" &&
    echo "$report"
)

# $1 - URL
# $2 - first hash
# $3 - second hash
is_ancestor_commit() (
    repo_cd "$1" &&
    git merge-base --is-ancestor "$2" "$3"
)

#-------------------------------------------------------------------------------
# INSTALLATION AND UNINSTALLATION
#-------------------------------------------------------------------------------

# $1 - URL
# $2 - hash
run_install() (
    version="$(beautify_hash "$1" "$2")" &&
    echod "installing version $version" &&

    repo_cd "$1" "$2" &&
    install_script="$(get_install_script)" &&
    get_uninstall_script > /dev/null && # GitPack must be able to uninstall it
    run_script "$install_script"
)

# $1 - URL
# $2 - hash
run_uninstall() (
    version="$(beautify_hash "$1" "$2")" &&
    echod "uninstalling version $version" &&

    repo_cd "$1" "$2" &&
    uninstall_script="$(get_uninstall_script)" &&
    run_script "$uninstall_script"
)

get_install_script() {
    if [ -x .install/install-"${ACCESS}-$SYSTEM" ]; then
        echo .install/install-"${ACCESS}-$SYSTEM"
    elif [ -x .install/install-"$ACCESS" ]; then
        echo .install/install-"$ACCESS"
    else
        echo 'E9: missing installation script' >&2; return 1
    fi
}

get_uninstall_script() {
    if [ -x .install/uninstall-"${ACCESS}-$SYSTEM" ]; then
        echo .install/uninstall-"${ACCESS}-$SYSTEM"
    elif [ -x .install/uninstall-"$ACCESS" ]; then
        echo .install/uninstall-"$ACCESS"
    else
        echo 'E10: missing uninstallation script' >&2; return 1
    fi
}

# $1 - script path
run_script() (
    echod "running script $1" &&
    DIAG_PREFIX='    ' &&
    "$1" 1>&2 && return # return if success, stdout considered diagnostic output

    script_status="$?"
    script_name="$(basename -- "$1")"
    echo "E11: $script_name script failed with $script_status" >&2
    return 1 # indicate error but do not propagate the exit status further
)

#-------------------------------------------------------------------------------
# STATUS DATABASE
#-------------------------------------------------------------------------------

# $1 - URL
get_status_record() {
    echod 'reading package database' &&
    db_select_first "$STATUS_PATH" "$STATUS_COL_URL" "$1"
}

# $1 - URL
# $2 - hash
insert_status_record() {
    echod 'adding to package database' &&
    echo "$1 $2" >> "$STATUS_PATH"
}

# $1 - URL
delete_status_records() (
    echod 'removing from package database' &&
    db="$(db_select_except "$STATUS_PATH" "$STATUS_COL_URL" "$1")" &&
    echon "$db" > "$STATUS_PATH"
)

# $1 - status record
status_record_url() {
    echo "$1" | cut -f "$STATUS_COL_URL" -d "$DB_DELIMITER"
}

# $1 - status record
status_record_hash() {
    echo "$1" | cut -f "$STATUS_COL_HASH" -d "$DB_DELIMITER"
}

#-------------------------------------------------------------------------------
# FETCHED DATABASE
#-------------------------------------------------------------------------------

# $1 - URL
fetched_recently() (
    current_time="$(get_current_time)" &&
    record="$(db_select_first "$FETCHED_PATH" "$FETCHED_COL_URL" "$1")" &&
    record_time="$(fetched_record_time "$record")" &&
    test "$record_time" = "$current_time"
)

# $1 - URL
mark_as_fetched_now() (
    current_time="$(get_current_time)" &&
    db="$(db_select_except "$FETCHED_PATH" "$FETCHED_COL_URL" "$1")" &&
    db="$(db_append_record "$db" "$1 $current_time")" &&
    echo "$db" > "$FETCHED_PATH"
)

get_current_time() {
    date -u '+%Y%m%d%H' # UTC as <year><month><day><hour>
}

# $1 - fetched record
fetched_record_time() {
    echo "$1" | cut -f "$FETCHED_COL_TIME" -d "$DB_DELIMITER"
}

#-------------------------------------------------------------------------------
# DATABASE FUNCTIONS
#-------------------------------------------------------------------------------

# $1 - database path
init_db() (
    db_dir="$(dirname -- "$1")" &&
    mkdir -p -- "$db_dir"/ &&

    if ! [ -e "$1" ]; then
        touch -- "$1"
    fi &&

    if ! [ -r "$1" ] || ! [ -w "$1" ]; then
        db_name="$(basename -- "$1")"
        echo "E14: cannot access $db_name database" >&2
        return 1
    fi
)

# $1 - database path
# $2 - key column
# $3 - expected value
db_select_first() (
    db="$(get_db "$1")" &&
    echon "$db" | while IFS= read -r record; do
        field="$(echo "$record" | cut -f "$2" -d "$DB_DELIMITER")" || return
        if [ "$field" = "$3" ]; then
            echo "$record"; return
        fi
    done
)

# $1 - database path
# $2 - key column
# $3 - filtered value
db_select_except() (
    db="$(get_db "$1")" &&
    echon "$db" | while IFS= read -r record; do
        field="$(echo "$record" | cut -f "$2" -d "$DB_DELIMITER")" || return
        if [ "$field" != "$3" ]; then
            echo "$record"
        fi
    done
)

# $1 - database path
get_db() {
    cat -- "$1"
}

# $1 - database
# $2 - record
db_append_record() {
    if [ "$1" ]; then
        echo "$1
$2"
    else
        echo "$2"
    fi
}

#-------------------------------------------------------------------------------
# CALL MAIN
#-------------------------------------------------------------------------------

main "$@"
