#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# https://github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

name: CI
on: [push, pull_request]

jobs:
  Analysis:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check source files
      run: |
        shellcheck src/gitpack
        shellcheck src/bash/gitpack-completion

    - name: Check test files
      run: |
        shellcheck test/run.sh
        shellcheck test/api/*
        shellcheck test/feature/*
        shellcheck test/xfail/*
        shellcheck test/helper/*

    - name: Check install files
      run: shellcheck .install/*

  Test:
    needs: Analysis
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: sh {0}
    env:
      MATRIX_OS: ${{matrix.os}}
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2

    - name: Run tests
      run: test/run.sh

    - name: Upload execution trace
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{matrix.os}}_gitpack-trace
        path: |
          gitpack-trace/failed_*
          gitpack-trace/passed_*
