#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# https://github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

name: CI
on: [push, pull_request]

jobs:
  Analysis:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check source files
      run: shellcheck src/*

    - name: Check test files
      run: |
        shellcheck test/run.sh
        shellcheck test/action/*

    - name: Check install files
      run: |
        shellcheck .gitpack/data/.bash_completion
        shellcheck .gitpack/install/local/precp

  Test:
    needs: Analysis
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2

    - name: Run tests
      run: test/run.sh
